/**
 * test/golden.ts: byte-for-byte snapshots of everything the cli writes.
 *
 * Runs each command over the fixture pages, normalizes the parts that are allowed to
 * differ between runs (the timestamp, the ephemeral port, absolute paths, the counter in
 * a generated class name), and compares the result against a committed file under
 * test/golden/. Any other difference fails.
 *
 * Run with: npm test. Rewrite the snapshots with: npm run test:golden -- --update.
 * Updating a golden produces a reviewable diff, which is the point: a change that claims
 * to alter nothing and moves a golden has found its own bug.
 */
import { mkdirSync, existsSync, readFileSync, writeFileSync, readdirSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { Checks, ROOT, HERE, runCli, startServer, startCrossOriginServer } from './harness';

const GOLDEN = join(HERE, 'golden');
const WORK = join(HERE, '.golden-work');

/** One snapshot: a cli invocation plus which of its outputs to record. */
interface Case {
	/** Snapshot file name stem, also the working output directory name. */
	name: string;
	/** Argv after the command, built from the live server base url. */
	args: (base: string, cdn: string, out: string) => string[];
	/** Files written under --out to snapshot, by name. */
	artifacts?: string[];
	/** Snapshot the printed JSON payload as well. */
	payload?: boolean;
}

/** Every page and format combination the snapshots cover. */
const CASES: Case[] = [
	// extract, all four agent-facing formats, over the button the fidelity bench also uses.
	...['html', 'tailwind', 'jsx', 'vue'].map((fmt): Case => ({
		name: `extract-sample-${fmt}`,
		args: (base, _cdn, out) => ['extract', `${base}/sample.html`, '--selector', '#login', '--format', fmt, '--out', out],
		artifacts: ['output.html'],
		payload: true,
	})),
	// An anchor styled as a button, on the page discovery cannot resolve into sections.
	...['html', 'tailwind'].map((fmt): Case => ({
		name: `extract-onepage-${fmt}`,
		args: (base, _cdn, out) => ['extract', `${base}/onepage.html`, '--selector', '.cta', '--format', fmt, '--out', out],
		artifacts: ['output.html'],
	})),
	// A card on the framework-shaped page: hashed class names, wrapper chains, a preflight reset.
	...['html', 'jsx'].map((fmt): Case => ({
		name: `extract-framework-${fmt}`,
		args: (base, _cdn, out) => ['extract', `${base}/framework.html`, '--selector', 'article', '--format', fmt, '--out', out],
		artifacts: ['output.html'],
	})),
	// A heading on the app-root page, which has a compact type scale and no media queries.
	{
		name: 'extract-app-html',
		args: (base, _cdn, out) => ['extract', `${base}/app.html`, '--selector', 'h1', '--out', out],
		artifacts: ['output.html'],
	},
	// The builder gate writes no artifact, so the payload is the whole contract.
	{
		name: 'extract-builder',
		args: (base, _cdn, out) => ['extract', `${base}/builder.html`, '--selector', '#hero', '--out', out],
		payload: true,
	},
	// candidates: the inventory an agent picks a selector out of.
	{
		name: 'candidates-sample',
		args: (base, _cdn, out) => ['candidates', `${base}/sample.html`, '--out', out],
		payload: true,
	},
	// schema, over every fixture page. framework.html takes the cross-origin sheet.
	...['sample', 'framework', 'app', 'onepage', 'builder'].map((page): Case => ({
		name: `schema-${page}`,
		args: (base, cdn, out) => [
			'schema',
			page === 'framework' ? `${base}/${page}.html?css=${encodeURIComponent(cdn)}` : `${base}/${page}.html`,
			'--out',
			out,
		],
		artifacts: ['schema.json', 'schema.md'],
	})),
];

/**
 * Replace everything that is allowed to differ between two runs of the same code.
 *
 * That is the generated timestamp, the version, the ephemeral server port, and absolute
 * paths. Nothing else. Generated `block__tag-n` class names are left alone: the pipeline
 * numbers them deterministically, so pinning them exactly catches a structural change
 * that a normalized name would hide.
 */
function normalize(text: string): string {
	// The repo path reaches the output three ways: as itself, with forward slashes, and
	// json-escaped. Only the run directory below it varies, so all three collapse to <ROOT>.
	const escaped = ROOT.replace(/\\/g, '\\\\');
	const forward = ROOT.replace(/\\/g, '/');
	return text
		.replace(/\r\n/g, '\n')
		.replace(/http:\/\/127\.0\.0\.1:\d+/g, 'http://127.0.0.1:PORT')
		// The cross-origin sheet reaches the schema url-encoded, inside a query string.
		.replace(/127\.0\.0\.1%3A\d+/g, '127.0.0.1%3APORT')
		.replace(/"at":\s*"[^"]*"/g, '"at": "<TIME>"')
		.replace(/"version":\s*"[^"]*"/g, '"version": "<VERSION>"')
		.replace(/^Generated by .*$/gm, 'Generated by <STAMP>')
		.split(escaped).join('<ROOT>')
		.split(forward).join('<ROOT>')
		.split(ROOT).join('<ROOT>')
		// Separators only inside a path we just anchored, so a css escape is left alone.
		.replace(/<ROOT>[^"\s]*/g, (path) => path.replace(/\\\\/g, '/').replace(/\\/g, '/'));
}

/** Drop the fields of a cli payload that name a path or a moment rather than a result. */
function normalizePayload(json: unknown): string {
	const clone = JSON.parse(JSON.stringify(json)) as Record<string, unknown>;
	for (const key of ['screenshot', 'artifact', 'schema', 'markdown', 'elementScreenshot']) delete clone[key];
	delete (clone['generated'] as Record<string, unknown> | undefined)?.['at'];
	delete (clone['generated'] as Record<string, unknown> | undefined)?.['version'];
	return normalize(`${JSON.stringify(clone, null, 2)}\n`);
}

/** The first few differing lines, with their line numbers, for a readable failure. */
function firstDiff(expected: string, actual: string, limit = 6): string {
	const a = expected.split('\n');
	const b = actual.split('\n');
	const out: string[] = [];
	for (let i = 0; i < Math.max(a.length, b.length) && out.length < limit * 2; i++) {
		if (a[i] === b[i]) continue;
		out.push(`    ${i + 1}- ${JSON.stringify(a[i] ?? '<missing>')}`);
		out.push(`    ${i + 1}+ ${JSON.stringify(b[i] ?? '<missing>')}`);
	}
	if (!out.length) return 'files differ only in trailing content';
	return `\n${out.join('\n')}`;
}

/** Compare one snapshot against its committed file, or rewrite it under --update. */
function compare(checks: Checks, update: boolean, file: string, actual: string): void {
	const path = join(GOLDEN, file);
	if (update) {
		writeFileSync(path, actual);
		process.stdout.write(`  wrote  ${file}\n`);
		return;
	}
	if (!existsSync(path)) {
		checks.check(`golden ${file}`, false, 'no committed snapshot; run npm run test:golden -- --update');
		return;
	}
	const expected = readFileSync(path, 'utf8').replace(/\r\n/g, '\n');
	checks.check(`golden ${file}`, expected === actual, expected === actual ? '' : firstDiff(expected, actual));
}

export async function main(): Promise<void> {
	const update = process.argv.includes('--update');
	if (!existsSync(join(ROOT, 'dist', 'cli', 'index.js'))) {
		process.stdout.write('cli not built; run `npm run build` first\n');
		process.exitCode = 1;
		return;
	}
	mkdirSync(GOLDEN, { recursive: true });
	rmSync(WORK, { recursive: true, force: true });
	const checks = new Checks();
	const { server, base } = await startServer();
	const cdn = await startCrossOriginServer();
	const written = new Set<string>();

	process.stdout.write(`\ngolden snapshots${update ? ' (updating)' : ''}:\n`);
	try {
		for (const c of CASES) {
			const out = join(WORK, c.name);
			const result = await runCli(c.args(base, cdn.url, out));
			if (c.payload) {
				const file = `${c.name}.payload.json`;
				written.add(file);
				compare(checks, update, file, normalizePayload(result.json));
			}
			for (const artifact of c.artifacts ?? []) {
				const path = join(out, artifact);
				const file = `${c.name}.${artifact}`;
				written.add(file);
				if (!existsSync(path)) {
					checks.check(`golden ${file}`, false, `cli wrote no ${artifact}: ${result.raw.slice(0, 160)}`);
					continue;
				}
				compare(checks, update, file, normalize(readFileSync(path, 'utf8')));
			}
		}

		// A snapshot no case produces any more is a snapshot nothing is checking.
		const orphans = readdirSync(GOLDEN).filter((f) => !written.has(f));
		if (update) for (const f of orphans) rmSync(join(GOLDEN, f));
		else checks.check('every committed golden belongs to a case', orphans.length === 0, orphans.join(', '));
	} finally {
		server.close();
		cdn.server.close();
	}

	if (update) {
		process.stdout.write(`\n${written.size} snapshots written to test/golden\n`);
		return;
	}
	if (!checks.report()) process.exitCode = 1;
}

main().catch((err) => {
	process.stdout.write(`golden harness crashed: ${(err as Error).message}\n`);
	process.exitCode = 1;
});
