/**
 * cli/src/schema-md.ts: render the page schema as a markdown reference.
 *
 * schema.json is the machine payload; schema.md is the human/prompt-facing summary an
 * agent can drop straight into a redesign prompt. Pure formatting over the schema the
 * inspector produced, defensive about optional fields so a thin page still renders.
 *
 * Everything the inspector measures renders here, one line each. The component blueprints used
 * to be extracted and then dropped, so a card spec that said `border: none` sat in schema.json
 * while the agent reading schema.md invented borders. Data that never reaches the reader may
 * as well not have been measured.
 *
 * The one thing held back is a fact the schema cannot place. A background effect names the
 * section it was seen in; one that names no section is left in schema.json and kept out of
 * here, because with nowhere attached it reads as permission to paint the effect anywhere,
 * which is drift the reader has no way to check.
 *
 * An unmeasured layout renders as `unknown (not measured)`, never as a default. The schema is
 * a hard contract, so a value it did not measure has to read as a gap and hand the decision
 * back to the agent's judgment.
 */
import type { BackgroundEffect, PageSchema, SectionBlueprint } from '../../core/src/inspect/schema/types';
import type { SchemaResult } from '../../core/src/schema';

/** Provenance stamp written into every schema output so an agent can spot a stale file. */
export interface SchemaStamp {
	by: 'snipcode';
	version: string;
	at: string;
}

/** Render tokens and layout into one markdown document. */
export function renderSchemaMd(result: SchemaResult, stamp: SchemaStamp): string {
	const { schema } = result;
	const lines: string[] = [];
	const push = (s = '') => lines.push(s);

	push(`# Design reference: ${schema.meta.title || schema.meta.url}`);
	push();
	push(`Source: ${schema.meta.url}  ·  viewport ${schema.meta.viewport.w}x${schema.meta.viewport.h}`);
	push(`Generated by ${stamp.by} ${stamp.version} at ${stamp.at}`);
	push();

	push('## Tokens');
	push();
	renderColors(schema, push);
	renderFonts(schema, push);
	renderScale(schema, push);
	push();

	push('## Layout');
	push();
	renderSections(schema, push);
	push();

	renderComponents(schema, push);

	return `${lines.join('\n')}\n`;
}

function renderColors(schema: PageSchema, push: (s?: string) => void): void {
	const colors = schema.tokens.colors ?? [];
	if (!colors.length) return;
	push('**Colors** (ranked by usage)');
	push();
	for (const c of colors.slice(0, 12)) {
		const contexts = c.contexts?.length ? `: ${c.contexts.slice(0, 3).join(', ')}` : '';
		push(`- \`${c.value}\`  ×${c.count}${contexts}`);
	}
	push();
}

function renderFonts(schema: PageSchema, push: (s?: string) => void): void {
	const fonts = schema.tokens.fonts ?? [];
	if (!fonts.length) return;
	push('**Fonts**');
	push();
	for (const f of fonts.slice(0, 6)) {
		const sizes = f.sizes?.length ? ` sizes ${f.sizes.slice(0, 8).join(', ')}` : '';
		const weights = f.weights?.length ? ` weights ${f.weights.join(', ')}` : '';
		push(`- ${f.family} (${f.usage})${sizes}${weights}`);
	}
	push();
}

function renderScale(schema: PageSchema, push: (s?: string) => void): void {
	const spacing = schema.tokens.spacing ?? [];
	const radii = schema.tokens.radii ?? [];
	const shadows = schema.tokens.shadows ?? [];
	if (spacing.length) push(`**Spacing**: ${spacing.slice(0, 12).join(', ')}`);
	if (radii.length) push(`**Radii**: ${radii.slice(0, 8).join(', ')}`);
	if (shadows.length) push(`**Shadows**: ${shadows.length} distinct`);
	const scale = schema.tokens.scaleAnalysis;
	if (scale) push(`**Type scale**: ${scale.name} (ratio ${scale.ratio}, base ${scale.base}px)`);
}

function renderSections(schema: PageSchema, push: (s?: string) => void): void {
	const sections = schema.sections ?? [];
	if (!sections.length) {
		push('_no section blueprint detected_');
		return;
	}
	for (const s of sections) {
		// layoutMeasured is optional only for a schema.json an older version wrote; a missing
		// flag is treated as measured so an old file still renders its layout.
		const measured = s.layoutMeasured !== false;
		const bits: string[] = [measured ? s.layout : 'unknown (not measured)'];
		if (measured && s.gridColumns) bits.push(`${s.gridColumns} cols`);
		if (measured && s.columnRatio) bits.push(`split ${s.columnRatio}`);
		if (s.maxWidth) bits.push(`max ${s.maxWidth}`);
		if (s.gap) bits.push(`gap ${s.gap}`);
		push(`- **${s.type}** (${s.tag}, ${s.alignment}): ${bits.join(', ')}`);
		const box: string[] = [`bg ${s.background}`];
		if (s.padding) box.push(`padding ${s.padding}`);
		push(`  - ${box.join(' · ')}`);
		if (s.elements?.length) push(`  - elements: ${s.elements.join(' · ')}`);
		// A repeating section is only rebuildable as numbers: how many items, how big one is,
		// and what it holds. The label on top of them barely matters once these are stated.
		if (s.items) {
			const shape = s.items.shape?.length ? ` (${s.items.shape.join(' + ')})` : '';
			push(`  - items: ${s.items.count} × ~${s.items.width}x${s.items.height}${shape}`);
		}
	}
}

/** Renders the component blueprints and the page's decorative and responsive language. */
function renderComponents(schema: PageSchema, push: (s?: string) => void): void {
	const buttons = schema.buttons ?? [];
	const cards = schema.cards ?? [];
	const nav = schema.nav;
	const decorative = schema.decorative;
	const breakpoints = schema.responsive?.breakpoints ?? [];
	if (!buttons.length && !cards.length && !nav && !decorative && !breakpoints.length) return;

	push('## Components');
	push();

	if (nav) {
		const bits = [`bg ${nav.bg}`, nav.position, `height ${nav.height}`];
		if (nav.border && nav.border !== 'none') bits.push(`border ${nav.border}`);
		if (nav.blur) bits.push('backdrop blur');
		push(`**Nav** (${nav.tag ?? 'nav'}): ${bits.join(', ')}`);
		push(`- ${nav.layout}, ${nav.linkCount} links`);
		push();
	}

	if (buttons.length) {
		push('**Buttons**');
		push();
		for (const b of buttons) {
			const bits = [`bg ${b.bg}`, `text ${b.color}`, `radius ${b.borderRadius}`, `padding ${b.padding}`, `${b.fontWeight} ${b.fontSize}`];
			if (b.border && b.border !== 'none') bits.push(`border ${b.border}`);
			if (b.shadow) bits.push(`shadow ${b.shadow}`);
			push(`- **${b.variant}** (${b.styleTag}): ${bits.join(', ')}`);
			const hover = Object.entries(b.hover ?? {});
			if (hover.length) push(`  - hover: ${hover.slice(0, 4).map(([k, v]) => `${k} ${v}`).join(', ')}`);
		}
		push();
	}

	if (cards.length) {
		push('**Cards**');
		push();
		for (const c of cards) {
			const bits = [`bg ${c.bg}`, `radius ${c.borderRadius}`, `border ${c.border}`, `shadow ${c.shadow}`, `padding ${c.padding}`];
			push(`- ${bits.join(', ')}`);
			push(`  - inner: ${c.innerLayout}`);
		}
		push();
	}

	if (decorative) {
		const bits: string[] = [`illustration ${decorative.illustrationStyle}`];
		const effects = locatedEffects(decorative.backgroundEffects ?? [], schema.sections ?? []);
		if (effects.length) bits.push(`effects ${effects.join(', ')}`);
		if (decorative.accentTreatments?.length) bits.push(`accents ${decorative.accentTreatments.join(', ')}`);
		push(`**Decorative**: ${bits.join(' · ')}`);
	}

	if (breakpoints.length) {
		const responsive = schema.responsive!;
		push(`**Breakpoints**: ${breakpoints.join(', ')} · mobile nav ${responsive.mobileNavStyle} · grids ${responsive.gridCollapseBehavior}`);
	}
	push();
}

/**
 * The background effects that name a section, each rendered as "gradient (hero)".
 *
 * An effect the schema could not place is left out. With nowhere attached it reads as
 * permission to paint the effect wherever convention suggests, which is how a rebuild put
 * gradients into a hero whose measured background is flat. Nothing is lost by dropping it: a
 * section actually painted as a gradient states the whole gradient on its own bg line, and the
 * unplaced entries stay in schema.json for anyone inspecting the measurement.
 */
function locatedEffects(effects: BackgroundEffect[], sections: SectionBlueprint[]): string[] {
	const names = sectionNames(sections);
	const out: string[] = [];
	for (const entry of effects) {
		const name = entry.section === undefined ? undefined : names[entry.section];
		if (name) out.push(`${entry.effect} (${name})`);
	}
	return out;
}

/**
 * One name per section: its type, carrying its position among sections of the same type when
 * the page has more than one, so "logos 2" always points at exactly one section.
 */
function sectionNames(sections: SectionBlueprint[]): string[] {
	const totals = new Map<string, number>();
	for (const s of sections) totals.set(s.type, (totals.get(s.type) ?? 0) + 1);

	const seen = new Map<string, number>();
	return sections.map((s) => {
		const nth = (seen.get(s.type) ?? 0) + 1;
		seen.set(s.type, nth);
		return (totals.get(s.type) ?? 0) > 1 ? `${s.type} ${nth}` : s.type;
	});
}
